# SPDX-FileCopyrightText: Alois Wohlschlager <wohlschlager@math.lmu.de>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "approximate"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.1.1"
