# SPDX-FileCopyrightText: Alois Wohlschlager <wohlschlager@math.lmu.de>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "karpenko"
version = "0.1.0"
edition = "2021"

[profile.release]
# this is academic research, we don't want silently incorrect results
overflow-checks = true
