# SPDX-FileCopyrightText: Alois Wohlschlager <wohlschlager@math.lmu.de>
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
  "generate-exact",
]
resolver = "2"

[profile.release]
# this is academic research, we don't want silently incorrect results
overflow-checks = true
